# Generated by Django 5.0.14 on 2026-08-15 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_paper_name', models.CharField(max_length=255)),
                ('master_answer_name', models.CharField(max_length=255)),
                ('rubric_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('answer_sheet_name', models.CharField(max_length=255)),
                ('total_score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='grading.gradingsession')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=10)),
                ('max_score', models.FloatField(default=5.0)),
                ('score_given', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('grading_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scores', to='grading.studentgradingresult')),
            ],
        ),
    ]
