# Generated by Django 5.0.14 on 2026-08-16 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsession',
            name='additional_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='criteria_source',
            field=models.CharField(choices=[('file', 'File'), ('manual', 'Manual')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='default_max_marks',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='evaluation_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='master_answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='question_paper_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='rubric_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing Context'), ('READY', 'Ready for Grading'), ('FAILED', 'Context Processing Failed')], default='READY', max_length=20),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='title',
            field=models.CharField(default='Untitled Grading Session', max_length=255),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentgradingresult',
            name='is_manually_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgradingresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gradingsession',
            name='master_answer_name',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gradingsession',
            name='rubric_name',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('answer_sheet_name', models.CharField(max_length=255)),
                ('answer_sheet_file', models.FileField(blank=True, null=True, upload_to='student_answers/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing AI Evaluation'), ('COMPLETED', 'Grading Completed'), ('FAILED', 'Evaluation Failed')], default='PENDING', max_length=20)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('current_stage', models.CharField(default='CREATED', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='grading.gradingsession')),
            ],
        ),
        migrations.AddField(
            model_name='studentgradingresult',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='grading.studentsubmission'),
        ),
    ]
