# Generated by Django 5.0.14 on 2026-08-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher')], default='TEACHER', max_length=10),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
