# Generated by Django 5.0.14 on 2026-08-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
