# Generated by Django 5.0.14 on 2026-08-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='indexing_status',
            field=models.CharField(choices=[('UNINDEXED', 'Unindexed'), ('PROCESSING', 'Processing'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='UNINDEXED', max_length=20),
        ),
    ]
